SOURCE_TRUST = {
    # Existing sources
    "reuters": 98,
    "bbc": 96,
    "bbc news": 96,
    "associated press": 97,
    "ap": 97,
    "nature": 99,
    "the hindu": 94,
    "indian express": 92,
    "the guardian": 94,
    "al jazeera": 90,
    "cnn": 88,
    "times of india": 88,
    "ndtv": 87,
    "npr": 92,
    "sciencedaily": 90,
    "deadline": 78,
    "yahoo entertainment": 75,
    "asiaone": 76,
    "tmz": 65,
    "punch newspapers": 72,

    # News agencies and major news organisations
    "al jazeera english": 90,
    "abc news & headlines – australian broadcasting corporation": 94,
    "abcnews.com": 90,
    "1news": 88,
    "7news": 84,
    "ait live": 76,
    "al-monitor": 85,
    "axios": 88,
    "bloomberg": 95,
    "cbc": 92,
    "cbs news": 88,
    "cnbc": 88,
    "financial times": 96,
    "fox business": 80,
    "fox news": 75,
    "haaretz": 87,
    "hindustan times": 86,
    "nbc news": 88,
    "pbs": 93,
    "politico": 90,
    "rnz": 92,
    "rte.ie": 91,
    "the associated press; feedloaderapi": 97,
    "the canadian press; feedloaderapi": 94,
    "the globe and mail": 91,
    "the irish times": 91,
    "the new york times": 94,
    "the wall street journal": 94,
    "the washington post": 93,
    "usa today": 85,

    # Technology publications
    "9to5google.com": 82,
    "android police": 80,
    "ars technica": 90,
    "bgr": 75,
    "boing boing": 72,
    "cnet": 84,
    "gizmodo": 76,
    "gsmarena.com": 82,
    "macrumors": 82,
    "notebookcheck.net": 80,
    "techcrunch": 84,
    "the verge": 84,
    "wired": 89,

    # Science and health publications
    "medical xpress": 86,
    "news-medical": 84,
    "phys.org": 88,
    "phys.org": 88,
    "sciencealert": 84,
    "space.com": 86,

    # Business and finance
    "business insider": 82,
    "business wire": 80,
    "businessline": 87,
    "forbes": 82,
    "marketbeat": 74,
    "the motley fool": 74,

    # Entertainment
    "billboard": 82,
    "hollywood reporter": 83,
    "page six": 65,
    "variety": 84,

    # Sports
    "afl.com.au": 85,
    "espn": 88,
    "espn philippines": 83,
    "goal.com": 80,
    "mlb.com": 88,
    "motorsport.com": 84,
    "nbc sports": 86,
    "sky sports": 88,
    "sportsnet.ca": 86,
    "yahoo sports": 78,

    # Regional publications
    "businessghana": 73,
    "citinewsroom.com": 76,
    "citizen digital": 77,
    "daily post nigeria": 70,
    "dw.com": 93,
    "gma network": 81,
    "inquirer.net": 81,
    "irish examiner": 86,
    "malaysiakini team": 82,
    "manila bulletin": 79,
    "premium times nigeria": 78,
    "pulse ghana": 72,
    "sahara reporters": 72,
    "the business standard": 80,
    "the express tribune": 78,
    "the guardian nigeria news": 75,
    "the jerusalem post": 81,
    "the straits times": 89,
    "thecable": 76,
    "tribune online": 70,
    "vanguard news": 72,
}

DEFAULT_TRUST_SCORE = 70