import os
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)

from .report_styles import (
    title_style,
    heading_style,
    normal_style,
    footer_style,
)


def generate_pdf(
    briefing: str,
    articles: list,
    output_path: str,
):
    """
    Generates a professional PDF report.

    Args:
        briefing (str): AI-generated executive summary.
        articles (list): List of retrieved news articles.
        output_path (str): Output PDF path.

    Returns:
        str: Path of the generated PDF.
    """

    # Create output directory if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Create PDF document
    doc = SimpleDocTemplate(output_path)

    # Store all PDF elements
    elements = []

    # ==========================
    # Report Title
    # ==========================
    elements.append(
        Paragraph(
            "NEWS INTELLIGENCE REPORT",
            title_style
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # Report Date
    # ==========================
    current_time = datetime.now().strftime("%d %B %Y %I:%M %p")

    elements.append(
        Paragraph(
            f"<b>Generated On:</b> {current_time}",
            normal_style
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # Executive Summary
    # ==========================
    elements.append(
        Paragraph(
            "Executive Summary",
            heading_style
        )
    )

    elements.append(
        Paragraph(
            briefing,
            normal_style
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # Top News Articles
    # ==========================
    elements.append(
        Paragraph(
            "Top News Articles",
            heading_style
        )
    )

    if not articles:

        elements.append(
            Paragraph(
                "No articles available.",
                normal_style
            )
        )

    else:

        for index, article in enumerate(articles, start=1):

            title = article.get("title", "N/A")
            source = article.get("source", "N/A")
            topic = article.get("topic", "N/A")
            author = article.get("author", "N/A")
            published = article.get("published_at", "N/A")
            trust_score = article.get("trust_score", "N/A")
            url = article.get("url", "N/A")

            elements.append(
                Paragraph(
                    f"<b>Article {index}</b>",
                    heading_style
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Title:</b> {title}",
                    normal_style
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Source:</b> {source}",
                    normal_style
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Topic:</b> {topic}",
                    normal_style
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Author:</b> {author}",
                    normal_style
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Published:</b> {published}",
                    normal_style
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Trust Score:</b> {trust_score}",
                    normal_style
                )
            )

            elements.append(
                Paragraph(
                    f"<b>URL:</b> {url}",
                    normal_style
                )
            )

            elements.append(Spacer(1, 15))

    # ==========================
    # Footer
    # ==========================
    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "Generated by News Intelligence Briefing Agent",
            footer_style
        )
    )

    # Build PDF
    doc.build(elements)

    return output_path